# Prometheus configuration for monitoring Supabase
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Docker containers metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']

  # PostgreSQL metrics (if pg_exporter is used)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']

  # Kong API Gateway metrics
  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: '/metrics'

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  # Custom health check endpoint
  - job_name: 'supabase-health'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/health'
    scrape_interval: 30s

  # Application metrics (if available)
  - job_name: 'supabase-api'
    static_configs:
      - targets: ['localhost:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
